site_name: Nautilus
site_description: Nautilus method for the FTO twisty puzzle
site_url: https://nautilusfto.com

theme:
  name: material
  logo: assets/Icon.png
  favicon: assets/Icon.png
  palette:
    # Light Mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark Mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs # Moves navigation links into the TOP HEADER bar
    - navigation.tabs.sticky # Keeps header bar pinned while scrolling
    - navigation.top # Adds a smooth "back-to-top" scroll button
    - navigation.prune # Remove left side navigation

extra_javascript:
  - path: https://cdn.cubing.net/v0/js/cubing/twisty
    type: module

plugins:
  - search
  - social

# Add markdown_extensions to allow raw HTML blocks
markdown_extensions:
  - md_in_html
  - extra
  - attr_list

# Extra CSS for header banner styling
extra_css:
  - stylesheets/extra.css

# Top Header Navigation Structure
nav:
  - Introduction: index.md
  - Step 1 - First Block: Step1.md
  - Step 2 - Centers: Step2.md
  - Step 3 - Last Triple: Step3.md
  - Step 4 - Last Layer: Step4.md
  - Baby Nautilus: BabyNautilus.md
  - Notation: Notation.md
  - Summary: Summary.md
  - Algorithms: Algorithms.md

extra:
  generator: false